[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
catppuccin = "2.4.0"
gpui.workspace = true
log.wokrspace = true
serde.workspace = true
serde_json.workspace = true
smallvec = "1.13.2"
windows = "0.57.0"
anyhow = "1"
