name: CI
on:
  pull_request:
  push:
    branches:
      - '*'
    tags:
      - '*'

# 添加权限设置
permissions:
  contents: write

jobs:
  test:
    name: Test
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install nightly rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt, clippy
      - name: Install dependencies
        run: |
          vcpkg integrate install
      - name: Setup | Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: windows-test-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Tools
        run: cargo install typos-cli || echo "typos-cli already installed"
      - name: Lint
        run: |
          cargo +nightly clippy -- --deny warnings
          typos
      - name: Build test
        run: |
          cargo +nightly test --all
